//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Recipe
    {
        public int Id { get; set; }
        [Display(Name = "Recipe Name")]
        public string Title { get; set; }
        [Display(Name = "Ingredients")]
        public string Ingridients { get; set; }
        public string Directions { get; set; }
        [Display(Name = "Preparation Time")]
        public string Prep_time { get; set; }
        [Display(Name = "Cooking Time")]
        public string Cooking_time { get; set; }
        [Display(Name = "# of Servings")]
        public int NumberOfServings { get; set; }
        [Display(Name = "Creator")]
        public int UserId { get; set; }
         [Display(Name = "Image")]
        public string ImgSrc { get; set; }
        [Display(Name = "Chef")]
        public virtual User User { get; set; }
    }
}
